export type DB = typeof import('./orm/Db');
import Env_1 = require("./config/Env");
import Route_1 = require("./route/Route");
import Db = require("./orm/Db");
import Log_1 = require("./log/Log");
import ProcessInfo_1 = require("./utils/ProcessInfo");
export declare let Config: import('log4js').Config;
export declare let Env: Env;
export declare let Route: Route;
export declare const Cache: any;
export declare const Auth: any;
export declare let Log: Log;
export declare const FileSystem: any;
export declare const Grpc: any;
export declare const Queue: any;
export declare const Schedule: any;
export declare let ProcessInfo: ProcessInfo;
export declare const Engine: any;
export declare const UpLo: any;
export { Db };
