module.exports = {
    Config: null,
    Env: null,
    Route: null,
    Cache: null,
    DB: null,
    Auth: null,
    Log: null,
    FileSystem: null,
    Grpc: null,
    Queue: null,
    Schedule: null,
    ProcessInfo: null,
    Engine: null,
    UpLo: null,
}
